shellcheck

diff --git a/.local/bin/startvnc b/.local/bin/startvnc
--- a/.local/bin/startvnc
+++ b/.local/bin/startvnc
@@ -6,6 +6,8 @@
 # version           :0.3
 # usage             :bash startvnc
 # notes             :install tigervnc-scraping-server (debian stretch)
+# shellcheck disable=SC2034
+
 
 # What's the script name
 SCRIPTNAME="startvnc"
@@ -48,7 +50,8 @@ NOTRUNNING="[\033[1;31mnot running\033[0m]"
 
 # Function to get the process id of the VNC Server
 fn_pid() {
-    CHECKPID=$(ps -fu ${USER} | grep "[x]$VNCSERVER" | awk '{print $2}')
+    #CHECKPID=$(ps -fu ${USER} | grep "[x]$VNCSERVER" | awk '{print $2}')
+    CHECKPID=$(pgrep -u "${USER}" "[x]$VNCSERVER" | head -1)
     if [[ ${CHECKPID} =~ ^[0-9]+$ ]] 
     then
         VAR=${CHECKPID}
@@ -59,14 +62,14 @@ fn_pid() {
 }
 
 
-if [ ! -d ${VNCDIR} ]
+if [ ! -d "${VNCDIR}" ]
 then
-    echo -e "Directory ${VNCDIR} doesn't exist. Create it first." ${FAILED}
+    echo -e "Directory ${VNCDIR} doesn't exist. Create it first. ${FAILED}"
     echo
     exit 1
 fi
 
-if [ ! -f ${PASSWDFILE} ]
+if [ ! -f "${PASSWDFILE}" ]
 then
     echo -e "${PASSWDFILE} doesn't exist. Create VNC password first. ${FAILED}"
     echo "Type \"vncpasswd\" to create passwd file."
@@ -84,99 +87,79 @@ fi
 case "$1" in
     start)
         echo -n "Starting VNC Server on display ${DISPLAY} "
-        fn_pid
-        if [ $? -eq 0 ]
-        then
-            echo -e ${FAILED}
+        if ! fn_pid; then
+            echo -e "${FAILED}"
             echo -e "VNC Server is running (pid: ${VAR})"
-	    echo
+            echo
         else
-            ${XVNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
-	    if [ $? -eq 0 ]
-	    then
-            	fn_pid
-            	echo ${VAR} > ${PIDFILE}
-            	echo -e ${OK}
-	    	echo
-	else
-		echo -e $FAILED
-		echo
-		fi
-
+	        if ! (exec ${XVNCSERVER} -display ${DISPLAY} -passwordfile "${PASSWDFILE}" -rfbport ${VNCPORT} >> "${LOGFILE}"); then
+                fn_pid
+            	echo "${VAR}" > "${PIDFILE}"
+            	echo -e "${OK}"
+                echo
+	        else
+                echo -e "$FAILED"
+                echo
+            fi
         fi
-
         ;;
     
     restart)
-
-        echo -n "Restarting VNC Server on display ${DISPLAY} "
+        echo -n "Restarting VNC Server on display ${DISPLAY}"
         fn_pid
-        if [ $? -eq 0 ]
-        then
-            kill -9 ${VAR}
-
-            if [ $? -eq 0 ]
-            then 
-                ${XVNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
-                echo -e ${OK}
-		echo
+        if ! fn_pid; then
+            if ! kill -9 "${VAR}"; then 
+                ${XVNCSERVER} -display ${DISPLAY} -passwordfile "${PASSWDFILE}" -rfbport ${VNCPORT} >> "${LOGFILE}" 2>&1 &
+                echo -e "${OK}"
+                echo
                 fn_pid 
-                echo ${VAR} > ${PIDFILE}
+                echo "${VAR}" > "${PIDFILE}"
                 exit 0
             else
-                echo -e ${FAILED}
+                echo -e "${FAILED}"
                 echo "Couldn't stop VNC Server. Exiting."
-		echo
+                echo
                 exit 1
             fi
-
         else
-
-            ${XVNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
-            if [ $? -eq 0 ]
-            then
-                echo -e ${OK}
-		echo
+            if ! (exec ${XVNCSERVER} -display ${DISPLAY} -passwordfile "${PASSWDFILE}" -rfbport ${VNCPORT} >> "${LOGFILE}") ; then
+                echo -e "${OK}"
+                echo
                 fn_pid
-                echo ${VAR} > ${PIDFILE}
+                echo "${VAR}" > "${PIDFILE}"
             else
-                echo -e ${FAILED}
+                echo -e "${FAILED}"
                 echo "Couldn't start VNC Server. Exiting."
-		echo
+                echo
                 exit 1
             fi
         fi
     ;;
 
     stop)
-    
         echo -n "Stopping VNC Server: "
-        fn_pid
-        if [ $? -eq 0 ]
-        then
-            kill -9 ${VAR}
-            echo -ne ${OK}
+        if ! fn_pid; then
+            kill -9 "${VAR}"
+            echo -ne "${OK}"
             echo -e " (pid: ${VAR})"
-	    echo
+            echo
         else
-            echo -e ${FAILED}
+            echo -e "${FAILED}"
             echo -e "VNC Server is not running."
-	    echo
+            echo
             exit 1
         fi
     ;;
 
     status)
         echo -n "Status of the VNC server: "
-        fn_pid
-        if [ $? -eq 0 ]
-        then
+        if ! fn_pid; then
             echo -e "$RUNNING (pid: $VAR)"
-	    echo
+            echo
             exit 0
         else
-            echo -e $NOTRUNNING
-	    echo
+            echo -e "$NOTRUNNING"
+            echo
         fi
         ;;
 
@@ -185,5 +168,5 @@ case "$1" in
         echo "Usage: $0 start|stop|restart|status"
         echo
         exit 1
-    ;;
+        ;;
 esac
